language: python
python:
  - "3.3"
install:
  - pip install -q flake8
  - pip install -r requirements.txt
before_script:
  - flake8 . --max-line-length=120 --max-complexity=10 --exclude='env,migrations,*.egg,docs'
script:
  - nosetests
